### PR TITLE
Feature/gps in poi

### PR DESCRIPTION
**Pull request by LazerTiberius**
Erweitert den POI Dialog mit der Möglichkeit seinen aktuellen Standpunkt zu nutzen

### CODE REVIEW

**Comment by CharlyUnicorn** [comment]
treffpunkt_gps

the function works very well and allows the use of meeting point and gps positioning in a single module - no errors detected in my test row

**Comment by werrolf** [comment]
Difficult review because of almost complete reformatting.  

Special case diff extraction for the two unmerged commits:
```sh
git show -b -w --ignore-space-at-eol 2c63931996564a923cb306d193e9a423e84d4925 93d18ca37374f4a83a43351679762f2073c5d443
```

**Comment by LazerTiberius** [comment]
Sorry, for this mess :(

**Comment by werrolf** [comment]
[Replacement pull open](https://github.com/mapbender/mapbender/pull/1015)

**Pull request closed without merging**
