### PR TITLE
Fix remaining old class references

### PR DESCRIPTION
**Pull request by Phocacius**
fixes 
- error when adding or editing users
- error when editing security settings for an application 
- ajax error when adding to print queue

### CODE REVIEW

**Comment by astroidex** [comment]
Testing
- add user works fine
- add group works  fine

error: Add Class ACL Application 
- /acl/edit?class=Mapbender\CoreBundle\Entity\Application
- browser freezes and does not add the user/group to 
- in the list the email is shown for user and not the name of the user

**Comment by Phocacius** [comment]
@astroidex Problems should be fixed, please test again.

**Comment by astroidex** [comment]
Tested again. Works fine. 
I did not test selfregister and resent password. @Phocacius  id you test that?

**Review by astroidex — APPROVED** [review]

**Comment by Phocacius** [comment]
No, I did not test that yet.

**Pull request merged**
