### PR TITLE
Bootstrap Update

### PR DESCRIPTION
**Pull request by PhilVanB**

### CODE REVIEW

**Comment by Phocacius** [comment]
grafik

In the layer editor when editing a vendor specific field, there is barely any margin between label and input field

**Comment by Phocacius** [comment]
grafik


The font size is now different between the custom dropdown and all other fields. Can the dropdown's font size be adjusted 
accordingly?

**Comment by Phocacius** [comment]
grafik

in Collection headers, the right-most action item (the trash in this case) is too far right without padding.   
There is unnecessary space to the right of the help icon

**Comment by Phocacius** [comment]
Sorry, wrong issue linked in https://github.com/mapbender/mapbender/commit/d1f87305c8d8a563beccb78038be8830f624d906, should have been 1502 instead of 1501

**Comment by PhilVanB** [comment]
@Phocacius I just added some commits that fix the design issues mentioned in your previous comments.

**Review by Phocacius — APPROVED** [review]

**Pull request merged**
