### PR TITLE
WMSLoader select children

### PR DESCRIPTION
**Pull request by simonseyock**

### CODE REVIEW

**Comment by simonseyock** [comment]
The `useDeclarative` property was not respected anymore in the current mapbender. This is fixed with commit e227f44

**Comment by astroidex** [comment]
I tested the branch. Works like expected. Please merge to the next release.

**Comment by astroidex** [comment]
Hi @simonseyock,
hab das Feature getestet. Läuft alles wie erwartet.

PR kann in die nächste Version rein: 
* https://github.com/mapbender/mapbender/pull/1045

**Comment by werrolf** [comment]
Merged 0544517039be4b13f9bb9a79ecedd70a314d097f, throwing away the rest.  
Apparently, that commit makes it so the root layer of the newly added WMS starts out selected in the Layer Tree (by not getting its treeOptions.selected reset to false).

**Pull request closed without merging**
