### PR TITLE
insert new osgeo logo

### PR DESCRIPTION
**Pull request by RobinSchwammborn**

### CODE REVIEW

**Comment by RobinSchwammborn** [comment]
Did it, see c900e01

**Comment by AxxL** [comment]
@werrolf Please review that small PR in our 4-eye-process. Thanks. :)

**Comment by eSlider** [comment]
@RobinSchwammborn, it's scaled in the hight. Logo compas looks like oval instead of circle. Yes, it's okay for everyone, but me. :)

**Comment by werrolf** [comment]
The OSGeo_project.png in this pull is not used anywhere except for mapbender/documentation, which has its own repository. Further, the only references to the file are absolute HTTP links to mapbender3.org, which occur exclusively in example markup in rsts.

There is absolutely no point in having this logo (even the old one) in the mapbender repository.

**Comment by astroidex** [comment]
* hi @werrolf as Mapbender is an OSGeo Project we added the  osgeo-logo to the code. We also use it in our workshops and demos. So it would be great to leave it in the repository.

**Comment by werrolf** [comment]
Because you need it on the server.
Upload it to the server.

**Comment by astroidex** [comment]
* hello @werrolf, I opened the ticket again, as I would really would like to keep the logo in the Mapbender code (we are talking about 12kb)

* Mapbender is an OSGeo Project and it is great to show it like this
* We could integrate the OSGeo Project logo to our demo applications (html-element: shows the image and links to http://osgeo.org) 
* use should use the file and do not link to a file in the internet, as some installations are offline

I could add the html-element to the yml -configuration for the demo applications

**Comment by werrolf** [comment]
And I'm closing the ticket again as I will not maintain files in the repo that have no relation to the code in the repo.
The old version will be removed too after some of the more important tasks have been completed.

**Comment by astroidex** [comment]
mb_demo

**Comment by astroidex** [comment]
ok. Thanks.

**Comment by werrolf** [comment]
That's just your installation with your customized config. We will not ship a bunch of unused assets just because somebody might decide to reference them in a customized environment.

There are many ways to add assets to your custom environment
* dump the files into your web folder
* hotlink the assets from the web
* make your own optional bundle and go nuts

**Pull request closed without merging**
