### PR TITLE
Feature/simpleSearch simpleSearch srs and label-string configurable

### PR DESCRIPTION
**Pull request by GeOSMRob**
An extension of the simple search:

- Now the objects can be transformed on the client side in projection.

- In the backend, the SRS can now be adjusted for the search

- In addition, it is possible to query Geojson objects via the search

- In addition, the label string in the backend can be adjusted by user-defined settings.

`properties.name + properties.street + properties.housenumber + properties.city + properties.postcode`

Example:

grafik

### CODE REVIEW

**Comment by astroidex** [comment]
Hi @GeOSMRob, is this solutionupdate compatible? At the moment you would refer to the column via "label" without properties.

**Comment by GeOSMRob** [comment]
Hi @astroidex, 
yes this solution is compatible with other search requests.
You can also compile the values from the request in the label field. 

This field is important because, for example, at photon geocoder dynamic resquest parameters exist.

Example from photon request:

- https://github.com/komoot/photon 

Request:
grafik

**Comment by astroidex** [comment]
Hi @GeOSMRob, great! Looks like a great improvement for the SimpleSearch element.

**Comment by werrolf** [comment]
This is a two-feature pull.  
GeoJSON is defined to a fixed CRS. Invalid GeoJSON sources are not Mapbender's problem.  
Your GeoJSON source can and should be configured to emit a document label. This is not Mapbender's problem.

**Pull request closed without merging**
