### PR TITLE
Make searchrouter results sortable

### PR DESCRIPTION
**Pull request by PhilVanB**
The following Searchrouter enhancements were added:

- sort result table by column
- configure initial sort column
- zoom to result extent
- highlight selected table row

Configure initial sort column like so:

- Add `sortBy` and `sortOrder` under result section in yaml-configuration:

```...
searchrouter:
  ...
  results:
     ...
     sortBy: columnName
     sortOrder: asc|desc
     ...
```

Configure zoom to result extent like so:

- Add `zoomToResultExtent` under result section in yaml-configuration:

```...
searchrouter:
  ...
  results:
     ...
     zoomToResultExtent: true
     ...
```

### CODE REVIEW

**Comment by astroidex** [comment]
I tested the feature. Looks very good.
- sorting works fine
- sort via sortBy works fine


Two remarks
- selected Feature in the Table is highligthed  (very good)  -> when you sort via a column -> the selection gets lost
- it is not very obvious that the columns can be sorted - any idea how to make it more obvious?

**Review by astroidex — APPROVED** [review]

**Comment by astroidex** [comment]
@PhilVanB and @astroidex discussed

- zoomToResultExtent: true will go to route. To make it configurable per route
- selection should be still there when the sorting is changed
- add icons to table header to see the possibility of sorting

**Review by astroidex — CHANGES_REQUESTED** [review]
remember sorting for next search does not work properly yet.

**Review by astroidex — APPROVED** [review]

**Review by astroidex — CHANGES_REQUESTED** [review]
Add Changelog Info

**Review by astroidex — APPROVED** [review]

**Review by Phocacius — APPROVED** [review]

**Pull request merged**
