### PR TITLE
Refactor WMTS and TMS sources

### LINKED ISSUE #1429: [BaseSourceSwitcher] does not allow to disable WMTS to disable them on start
**Describe the bug**
BaseSourceSwitcher can handle WMS/WMTS as Background services and provide buttons or radiobuttons to swicth. On start the services should be activated that are active in the Instance configuration.

- For WMS you can deactivate the root layer -> the WMS will not be active on STart
- Problem: For WMTS you can not disable a WMTS on start. If you do it is not possible to activate the WMTS again
- Problem: like this all WMTS are active on start of an application
- The radio buttons do not show the status on start - it loosk like no service is active

**To Reproduce**
1. Load WMTS like
  - https://basemap.de/dienste/wmts_capabilities_web_raster_schummerung.xml
  - https://basemap.de/dienste/wmts_capabilities_web_raster.xml 
2. Configure the application with BaseSourceSwitcher
4.Frontend  See: all WMTS are active on start
5. Frontend : you can not see which service is active (no radiobutton selected) but all WMTS are requested
5. Backend: it is not possible to deactivate a WMTS root layer

**Expected behavior**
It should be configurabe which WMTS is active on start of the application

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.1, 3.3.2 rc1
 - 
**Screenshots / Logmessage**
wmts_notactive

start

### LINKED ISSUE #1432: [overview] WMTS can not be used as overview Service
**Describe the bug**
If you add a WMST to the overview element the application fails to load with an error "Element 3851 failed to initialize: source.hasVisibleLayers is not a function "

Bildschirmfoto vom 2022-09-28 12-35-51

**To Reproduce**
1. Load a WMTS for example https://www.wmts.nrw.de/geobasis/wmts_nw_dop/1.0.0/WMTSCapabilities.xml?Version=1.0.0&Service=WMTS&Request=getCapabilities
2. Add the WMSt to your applictaion to the overview element

**Expected behavior**
WMTS should also be usable in overview

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.1, 3.3.2rc1

### PR DESCRIPTION
**Pull request by Phocacius**
Refactored WMTS and TMS sources to also have a root element. This allows showing and toggling of sub-layers in the layer tree. The "fake root" element that was used in earlier Mapbender versions was removed.

:warning: If you used WMTS or TMS services in earlier versions, refresh them using the backend after the upgrade to Mapbender 4
:warning: Even if you are upgrading from 4.0-beta1, you need to perform a schema update: `bin/console doctrine:schema:update --complete --force`

Fixes #1429
Fixes #1432

### CODE REVIEW

**Review by swinkelmann — APPROVED** [review]
Looks good to me.

**Review by astroidex — CHANGES_REQUESTED** [review]
- add WMTS works fine
- configuration WMTS works fine
   - some options are not necessary maybe?
   - opacity is missing 
 - layertree with thematic layer: when the layerset is deactivated the WMTS is still visible 

problems
- overview with WMTS: print fails when the template provides an overview frame
-  error when you try to deactivate a WMTS instance in a layerset (close eye) or when you want to move it to another layerset

Bildschirmfoto vom 2024-06-03 17-56-36

**Comment by Phocacius** [comment]
Fixes all problems related to WMTS. 

The TMS problems won't be fixed for the Mapbender 4 release but be part of a future bugfix release.

**Comment by astroidex** [comment]
- Error when you try to move a Shared Instance WMS/WMTS to another layerset. it works fine with a private instance
- please check print overview WMTS

**Review by astroidex — CHANGES_REQUESTED** [review]
see comments

**Review by astroidex — APPROVED** [review]

**Pull request merged**
