### PR TITLE
Make side pane user-resizable

### PR DESCRIPTION
**Pull request by Phocacius**
Adds an option to the side pane region's properties in the default Fullscreen template:

grafik

It is active by default. The key for yaml applications is `resizable`.

Users can now drag the side pane on its right edge to make it smaller or larger. 

By default, the minimum size is 120px. the maximum is 95% of the screen's width. These values can be further restricted by using custom css:

```css
.sidePane.resizable {
  min-width: 200px;
  max-width: 500px;
}
```

### CODE REVIEW

**Comment by astroidex** [comment]
I tested the feature.

- only works with sidepane position left. When you switch to right it does not work
- border of sidepane is bigger when activated. Is that mandatory? or could it only be bigger on mouse over?
- also effect with many buttons see screenshot

sidepane

**Comment by Phocacius** [comment]
- I'd leave it as default. It does affect all existing applications, however it's only an enhancement, it doesn't break existing applications
- Right position is now supported
- border is weakened
- overlap occurs when a single word is very long, maybe add to the documentation that a shy character (https://unicode-explorer.com/c/00AD) can be included in the title to auto-enable hyphenation

**Comment by astroidex** [comment]
works fine

**Review by astroidex — APPROVED** [review]

**Comment by Phocacius** [comment]
The update of jquery-ui-touch-punch should also fix #1506, @astroidex please check that again.

**Comment by astroidex** [comment]
works fine with firefox and chrome

**Pull request merged**
