### PR TITLE
Fix remove layerset translation notification

### PR DESCRIPTION
**Pull request by eSlider**
* Fix translation title by layer set instance removing. Closing: #694

### CODE REVIEW

**Comment by werrolf** [comment]
I like.
Checking the yaml translations...

**Comment by werrolf** [comment]
Locales de, es, en, fr, it: good (separate ´´´.title´´´ and ´´´.confirm´´´ under ´´´mb.manager.admin.instance.delete´´´)
Locales pt, nl, ru: bad (´´´mb.manager.admin.instance.delete``` is a single-string leaf node).

**Comment by werrolf** [comment]
Hint:
```
ron@flake:~/proj/mb306/application/mapbender$ grep -A10 -P '^\s*instance:\s*$' `find . -name 'messages.*.yml'` | grep -A2 delete:
./src/Mapbender/ManagerBundle/Resources/translations/messages.pt.yml-        delete: 'Remover instância'
./src/Mapbender/ManagerBundle/Resources/translations/messages.pt.yml-        add: 'Adicionar instância'
./src/Mapbender/ManagerBundle/Resources/translations/messages.pt.yml-        show_hide: 'Instância ligada/desligada'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.es.yml-        delete:
./src/Mapbender/ManagerBundle/Resources/translations/messages.es.yml-          title: 'borrar instancia'
./src/Mapbender/ManagerBundle/Resources/translations/messages.es.yml-          confirm: '¿Realmente quieres quitar la instancia de título <span class="italic">%instance_title%</span>?'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.nl.yml-        delete: 'verwijder instance'
./src/Mapbender/ManagerBundle/Resources/translations/messages.nl.yml-        add: 'Voeg instance toe'
./src/Mapbender/ManagerBundle/Resources/translations/messages.nl.yml-        show_hide: 'Wissel toon/verberg instance'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml-        delete: 'Delete source'
./src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml-        new:
--
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml-        delete:
./src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml-          title: 'delete instance'
./src/Mapbender/ManagerBundle/Resources/translations/messages.en.yml-          confirm: 'Do you really want to remove the instance with the title <span class="italic">%instance_title%</span>?'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml-        delete: 'Delete source'
./src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml-        new:
--
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml-        delete:
./src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml-          title: 'delete instance'
./src/Mapbender/ManagerBundle/Resources/translations/messages.fr.yml-          confirm: 'Do you really want to remove the instance with the title <span class="italic">%instance_title%</span>?'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml-        delete: 'Datenquelle entfernen'
./src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml-        new:
--
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml-        delete: 'Instanz löschen'        
./src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml-        no_instance_added: 'Keine Instanz vorhanden'
./src/Mapbender/ManagerBundle/Resources/translations/messages.de.yml-        no_layer_added: 'Keine Ebene hinzugefügt'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.ru.yml-        delete: 'Удалить образец'
./src/Mapbender/ManagerBundle/Resources/translations/messages.ru.yml-        add: 'Добавить образец'
./src/Mapbender/ManagerBundle/Resources/translations/messages.ru.yml-        show_hide: 'Вкл/выкл образец'
--
./src/Mapbender/ManagerBundle/Resources/translations/messages.it.yml-        delete:
./src/Mapbender/ManagerBundle/Resources/translations/messages.it.yml-          title: 'elimina istanza'
./src/Mapbender/ManagerBundle/Resources/translations/messages.it.yml-          confirm: 'Sei sicuro di voler rimuovere l''istanza con il titolo <span class="italic">%instance_title%</span>?'
```

**Comment by werrolf** [comment]
Ima go fix this.
I think we still have the old title / confirm translations in the history.
Also going to try and find the proper French translations (the messages in messages.fr.yml are English!)

**Comment by eSlider** [comment]
@werrolf don't forget to reuse this branch (fix/remove-layersets-translation-notification) to bring you fixes in :)

**Comment by werrolf** [comment]
Commit has been cherry-picked into hotfix/translations.
New commit hash 4e8bab46bd68fb26683df1beef80c5fcddc29e2d

**Pull request closed without merging**
