### PR TITLE
yStartPosition only checked when legend-frame exits

### PR DESCRIPTION
**Pull request by astroidex**
* see ticket #555
* Print should not fail when no legend region on first page exists

### CODE REVIEW

**Comment by eSlider** [comment]
@swinkelmann, please check this.

**Comment by astroidex** [comment]
test worked fine. PDF was created: https://github.com/mapbender/mapbender/issues/555#issuecomment-315060044

Scenario was defined in the PR see above:

> Print should not fail when no legend region on first page exists

**Comment by astroidex** [comment]
* maybe with some constellations (maybe PHP 7.x or something else) the print failed before

**Comment by astroidex** [comment]
* Please check #555 https://github.com/mapbender/mapbender/issues/555
* sorry - I can't reproduce the error on my system. Some systems exit with the error if yStartPosition is called without declare it first (this is what I fixed with the patch)
* please merge this patch, as mb-user call/mail me and tell me about print problems in 3.0.6.3 -> I give them the patch and print works fine

**Comment by swinkelmann** [comment]
All merge conflicts solved. 
Successfully tested with template 'A4 landscape'.

@eSlider please merge

**Comment by eSlider** [comment]
@swinkelmann, do you confirm, this you have test it with the workflow https://github.com/mapbender/mapbender/issues/555#issuecomment-325924196?

**Comment by CharlyUnicorn** [comment]
Hello, 
I tested it with the workflow from https://github.com/mapbender/mapbender/issues/555 
It works fine!

**Comment by swinkelmann** [comment]
Confirmed. Ready to merge.

**Comment by AxxL** [comment]
VETO.

#555 is not completely solved. The effect doesn't occur in any of my mapbender installations, except when I start from bootstrap.

**Comment by eSlider** [comment]
@AxxL, ok I agree with you veto, and I revert branch changes from  https://github.com/mapbender/mapbender/commits/hotfix/printclient-legend-ystartposition in https://github.com/mapbender/mapbender/commits/release/3.0.6 branch. 
I will check this next week, if I bekome time to doing that.

**Pull request merged**
