### PR TITLE
Fix displaying scale value in scale selector

### PR DESCRIPTION
**Pull request by eSlider**
* Fix displaying scale value in scale selector
* Clean scaleselector element JS code

Closes: #647
Associated: #595

### CODE REVIEW

**Comment by CharlyUnicorn** [comment]
The scale display on the scale selector and the fix displaying in the bar on the right and in the map respond correctly. Nice work. 
Tested with two different ALKIS-WMS.

auswahl_251




The only problem/change request I noticed is the display of the scale in the map. The element is probably rounded and therefore in the example screen shot instead of the 1: 100500 a 1: 101K appears, which could possibly confuse some users. Here you could think about a configuration possibility in the administration, which allows the selection of the rounding and display behavior.

**Comment by astroidex** [comment]
Hi @eSlider hi @CharlyUnicorn thanks for the fix and the testing. I will have a look at it next week.

**Comment by eSlider** [comment]
@CharlyUnicorn,  101K isn't a bug RTM: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Math/round

**Comment by eSlider** [comment]
@CharlyUnicorn, one more, the bug I fixed depends on scale selector behavior, not on scale display element.

**Comment by eSlider** [comment]
@werrolf ping.

**Comment by werrolf** [comment]
Huh?

**Pull request merged**
